// IllMeshViewer headless test runner. CTest invokes one case per process.

#include <Illumo/Testing/TestRegistry.h>
#include <cctype>
#include <cstdio>
#include <exception>
#include <filesystem>
#include <fstream>
#include <string>

void
registerMeshViewerConfigTests(IllumoTestRegistry& registry);
void
registerMeshViewerCameraTests(IllumoTestRegistry& registry);
void
registerMeshViewerUiTests(IllumoTestRegistry& registry);
void
registerMeshViewerModuleTests(IllumoTestRegistry& registry);

static IllumoTestRegistry
createRegistry()
{
  IllumoTestRegistry registry;
  registerMeshViewerConfigTests(registry);
  registerMeshViewerCameraTests(registry);
  registerMeshViewerUiTests(registry);
  registerMeshViewerModuleTests(registry);
  return registry;
}

static int
runTestCase(const IllumoTestCase& testCase)
{
  std::printf("\n======== %s ========\n", testCase.name.c_str());

  try {
    const int failures = testCase.function();
    std::printf("======== %s: %s (%d failure(s)) ========\n",
                testCase.name.c_str(),
                failures == 0 ? "PASSED" : "FAILED",
                failures);
    return failures == 0 ? 0 : 1;
  } catch (const std::exception& exception) {
    std::printf("FAIL: unhandled exception: %s\n", exception.what());
  } catch (...) {
    std::printf("FAIL: unhandled non-standard exception\n");
  }

  return 1;
}

static int
runAllTests(const IllumoTestRegistry& registry)
{
  int failures = 0;
  for (const IllumoTestCase& testCase : registry.getTestCases()) {
    failures += runTestCase(testCase);
  }

  std::printf("\n==== %s (%d failing test case(s)) ====\n",
              failures == 0 ? "ALL PASSED" : "FAILED",
              failures);
  return failures == 0 ? 0 : 1;
}

static int
writeCTestFile(const IllumoTestRegistry& registry,
               const std::string& outputPath,
               const std::string& executablePath,
               const std::string& workingDirectory)
{
  std::ofstream output(outputPath, std::ios::trunc);
  if (!output.is_open()) {
    std::printf("Unable to write CTest discovery file: %s\n",
                outputPath.c_str());
    return 1;
  }

  output << "# Generated by IllMeshViewerTests --write-ctest.\n";
  for (const IllumoTestCase& testCase : registry.getTestCases()) {
    std::string safeName = testCase.name;
    for (char& character : safeName) {
      if (!std::isalnum(static_cast<unsigned char>(character))) {
        character = '_';
      }
    }

    const std::filesystem::path caseDirectory =
      std::filesystem::path(workingDirectory) / "Testing" / "IllMeshViewer" /
      safeName;
    std::error_code directoryError;
    std::filesystem::create_directories(caseDirectory, directoryError);
    if (directoryError) {
      std::printf("Unable to create test working directory: %s\n",
                  caseDirectory.string().c_str());
      return 1;
    }

    output << "add_test([==[" << testCase.name << "]==] [==[" << executablePath
           << "]==] --run [==[" << testCase.name << "]==])\n";
    output << "set_tests_properties([==[" << testCase.name
           << "]==] PROPERTIES WORKING_DIRECTORY [==[" << caseDirectory.string()
           << "]==] LABELS [==[IllMeshViewer;IllumoWorkspace]==] TIMEOUT "
           << testCase.timeoutSeconds << ")\n";
  }

  if (!output.good()) {
    std::printf("Failed while writing CTest discovery file: %s\n",
                outputPath.c_str());
    return 1;
  }

  return 0;
}

int
main(int argc, char** argv)
{
  const IllumoTestRegistry registry = createRegistry();

  if (argc > 1 && std::string(argv[1]) == "--list") {
    for (const IllumoTestCase& testCase : registry.getTestCases()) {
      std::printf("%s\n", testCase.name.c_str());
    }
    return 0;
  }

  if (argc > 2 && std::string(argv[1]) == "--run") {
    const std::string targetName = argv[2];
    for (const IllumoTestCase& testCase : registry.getTestCases()) {
      if (testCase.name == targetName) {
        return runTestCase(testCase);
      }
    }

    std::printf("FAIL: test case '%s' was not found\n", targetName.c_str());
    return 1;
  }

  if (argc > 4 && std::string(argv[1]) == "--write-ctest") {
    return writeCTestFile(registry, argv[2], argv[3], argv[4]);
  }

  return runAllTests(registry);
}
