#include "CellGameModule.h"
#include "BuiltinPatterns.h"
#include "MainMenuModule.h"
#include "PatternCodec.h"
#include "Rulesets/WireworldRuleSet.h"
#include <Illumo/Engine/IModuleHost.h>
#include <Illumo/Gui/GuiKit.h>
#include <Illumo/Platform/Clipboard.h>
#include <Illumo/Platform/SaveLoad.h>
#include <Illumo/Rendering/Camera.h>
#include <Illumo/Rendering/Primitives/MeshVisual.h>
#include <Illumo/Rendering/Primitives/UiTheme.h>
#include <Illumo/Services/InputManager.h>
#include <Illumo/Services/Logger.h>
#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fstream>
#ifdef _WIN32
#include <windows.h>
#endif
#include <glm/gtc/matrix_transform.hpp>
#include <new>
#include <queue>
#include <random>
#include <sstream>
#include <vector>
